### ISSUE TITLE
Windows.UI.Notifications ToastNotification event listener not working

### ISSUE THREAD

**Issue by MarkTiedemann** [NodeRT/NodeRT#36] opened 2016-09-04 20:18 UTC
The code below produces the following console output: `FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.`

```js
const dom = require('./prebuilt/windows.data.xml.dom')
const notifications = require('./prebuilt/windows.ui.notifications')

const xml = new dom.XmlDocument()
xml.loadXml( ... )

const toast = new notifications.ToastNotification(xml)
toast.on('dismissed', () => console.log('dismissed'))

const notifier = notifications.ToastNotificationManager.createToastNotifier( ... )
notifier.show(toast)
```

Running the code without the `dismissed` event listener works just fine.

Any ideas on how to fix this? Help would be much appreciated. 

*// Win 10, Node 6, VS 2015*

**Comment by nadavbar** [comment] 2016-09-04 20:27
Thanks for reporting this, seems like one of the artifacts of the APIs changes to NaN, will take a look and hopefully will have a fix soon

**Comment by nadavbar** [comment] 2016-09-05 07:35
It seems like there was a general issue with events registration, It is now fixed (commit: 72993fd)
The latest release (2.0.1) contains the fix.
Thanks for reporting this issue and let me know if you see any more issues

**Comment by MarkTiedemann** [comment] 2016-09-05 14:54
Many, many thanks for fixing this so quickly!

There is one unexpected behavior, though: The toast's even emitter does not seem to keep the event loop running. Therefore, as a workaround, I have to use a long-running keep-alive timeout (which I clear upon an activated, dismissed or failed event) to be able to receive the events.

**Comment by nadavbar** [comment] 2016-09-05 19:43
In the current version, this behavior is by design, since WinRT events tends to be pretty chatty. (think data events coming from the accelerometer)
It's actually a good question regarding the use case and the expected behavior. It might be a good time to rethink this though. I've adde issue #38 in order to track this.

**Closed** 2016-09-05 20:24 UTC

**Comment by MarkTiedemann** [comment] 2016-09-06 16:55
I've put the code of my little experiment into a [node module](https://github.com/MarkTiedemann/win10-toast) [available on npm](https://www.npmjs.com/package/win10-toast) if anyone looking at this issue is interested in it.
